### ISSUE TITLE
Almost everything is red

### ISSUE THREAD

**Issue by Murriouz** [karyfoundation/kf-theme-vscode#1]
Here's some code in my js file.

![image](https://cloud.githubusercontent.com/assets/4125903/17855294/8f9177f8-68aa-11e6-8daa-6e6a532728b4.png)

As you can see, almost everything is red. And this does't look so good...

**Comment by pmkary** [comment]
Thanks a lot for using our theme!

If your code is open-source can I test it on my machine? because these color must render as foreground (almost black) color and only the definitions should be red! And we have not seen something like this like ever.

However what definitions are you using? because there is an [Atom Grammar Definition for JavaScript](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) and I don't know what happens if you do that (We have a port for an atom that works correctly on atom itself but I don't know if works good on atom too)

Anyways this is too strange and I hope we can get it right. So if you provide me with some details on your configurations I'll be too happy.

**Comment by Murriouz** [comment]
I'm sorry my code is not open-source.
I'm using Javascript Babel definitions. And in atom I'm using babel as well. This theme looks a bit good in atom but not as good as it's in it's screenshots. Here's how it looks like in atom with the same code.

![image](https://cloud.githubusercontent.com/assets/4125903/17877066/a1c7e11a-6912-11e6-8883-e0338bbb2d30.png)

I think you can try some es6 and react code and it can re-produce the issue.

Here's some sample code.

```javascript
import { EventEmitter } from 'events';
import React, {Component} from 'react'

const EventCaster = new EventEmitter();

const Events = {
  ReachSize: 'reachSize'
};

class componentName extends Component {
  constructor() {
    super();
    this.state = {};
  }

  componentDidMount () {
    this.getSize = this.getSize.bind(this);

    EventCaster.addListener(Events.ReachSize, this.getSize);
  }

  componentWillUnmount () {
    EventCaster.removeListener(Events.ReachSize, this.getSize);
  }
  

  getSize() {
    return {
      width: 10,
      height: 10
    };
  }

  render () {
    return (
      <div>
        { this.state.content }
      </div>
    )
  }
}

export default componentName
```

And it looks like this in vscode:
![image](https://cloud.githubusercontent.com/assets/4125903/17877171/8c047ac2-6913-11e6-97f1-b6cb6b5e6e3e.png)

**Comment by pmkary** [comment]
Thanks a lot for your feedback.

If you use vscode's standard javascript+react syntax look you'll get good results:

![](https://cloud.githubusercontent.com/assets/2157285/17884678/c4bddae6-692e-11e6-90ac-a2bd1f10d386.png)
![](https://cloud.githubusercontent.com/assets/2157285/17884679/c4cb47f8-692e-11e6-8833-f232dab23068.png)

I'll be testing it on Babel to see what happens, hope it leads to some results for you :D
Thanks a lot!

**Comment by pmkary** [comment]
Okay right! It's babel! They have implement the definition so not right! but don't worry we'll make the theme compatible!

**Comment by Murriouz** [comment]
Yes, using standard javascript+react syntax looks good. But babel provide better es6 and react support so I still want to use it.
Thanks very much for making it compatible with babel!

**Comment by pmkary** [comment]
You're welcome, I'm a bit busy right now but in the next release I'll implement that. I think maybe in a week or two it be stable enough.

**Comment by pmkary** [comment]
You're welcome, I'm a bit busy right now but in the next release I'll implement that. I think maybe in a week or two it be stable enough.

**Comment by Murriouz** [comment]
That's fine. I understand, and I can wait. :)

**Comment by Murriouz** [comment]
Another little problem. When using with vscode default javascript grammer and react, the curly braces in component render function have different color.

![image](https://cloud.githubusercontent.com/assets/4125903/18043613/94a2f658-6dfb-11e6-8bdf-997fd8fff382.png)

**Comment by pmkary** [comment]
let me see what I can do...

**Comment by pmkary** [comment]
Also if you could please report the new issues [here](https://github.com/karyfoundation/karyfoundation.themeX) that would be really cool

**Comment by pmkary** [comment]
@Murriouz: First of all I have to make a big excuse here. I said I'll fix this in one or two weeks but the stuff got so much and I got so busy. However I wanted to give you some ideas of the next release. Good news for you is that the Babel Definitions will be the default definitions for the vscode 1.7 I guess. If you download the latest insiders build of vscode you get what I mean. And for the problem this is how the fixed editon looks on the vscode insiders:

<img width="727" alt="screen shot 2016-10-22 at 2 58 21 am" src="https://cloud.githubusercontent.com/assets/2157285/19614631/f5ff1fbc-9803-11e6-9296-1fb21020b09f.png">

As you can see now the object keys also have their own color. And also I'm trying to find better colors for most of the stuff there. So I think soon there will be the next release. 

Thank you for using the themes 👍

**Comment by pmkary** [comment]
So you can now enjoy the new themes.

**Comment by Murriouz** [comment]
Thanks for the update. It looks great now.

**Comment by pmkary** [comment]
@Murriouz I'm happy to hear :D 

This is the final version (7.2) that is available now for update:

<img width="839" alt="screen shot 2016-10-22 at 11 46 34 am" src="https://cloud.githubusercontent.com/assets/2157285/19618262/f3ec9ae4-9851-11e6-9e82-d24cadbbedcc.png">

![screen shot 2016-10-22 at 12 21 42 pm](https://cloud.githubusercontent.com/assets/2157285/19618269/2718a926-9852-11e6-98b1-c91d23a741c8.png)

I hope you enjoy 😄
